# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\InputDataWindow\inputData.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputData(object):
    def setupUi(self, InputData):
        InputData.setObjectName("InputData")
        InputData.resize(966, 900)
        InputData.setMinimumSize(QtCore.QSize(966, 856))
        InputData.setMaximumSize(QtCore.QSize(966, 900))
        self.resultList = QtWidgets.QListWidget(InputData)
        self.resultList.setGeometry(QtCore.QRect(17, 550, 931, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.resultList.setFont(font)
        self.resultList.setObjectName("resultList")
        self.propertyList = QtWidgets.QListWidget(InputData)
        self.propertyList.setGeometry(QtCore.QRect(15, 80, 431, 381))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.propertyList.setFont(font)
        self.propertyList.setObjectName("propertyList")
        self.viewKnowledgeBase = QtWidgets.QPushButton(InputData)
        self.viewKnowledgeBase.setGeometry(QtCore.QRect(20, 820, 211, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewKnowledgeBase.setFont(font)
        self.viewKnowledgeBase.setObjectName("viewKnowledgeBase")
        self.determineTypeAlloy = QtWidgets.QPushButton(InputData)
        self.determineTypeAlloy.setGeometry(QtCore.QRect(750, 820, 201, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.determineTypeAlloy.setFont(font)
        self.determineTypeAlloy.setObjectName("determineTypeAlloy")
        self.scrollArea_2 = QtWidgets.QScrollArea(InputData)
        self.scrollArea_2.setGeometry(QtCore.QRect(470, 80, 480, 380))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(470, 380))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(550, 390))
        self.scrollArea_2.setBaseSize(QtCore.QSize(550, 390))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 457, 378))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 551, 391))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.listWidget_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.listWidget_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.listWidget_4.setContentsMargins(0, 0, 0, 0)
        self.listWidget_4.setSpacing(1)
        self.listWidget_4.setObjectName("listWidget_4")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.label = QtWidgets.QLabel(InputData)
        self.label.setGeometry(QtCore.QRect(300, 20, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(InputData)
        self.label_2.setGeometry(QtCore.QRect(330, 490, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.clearInputValues = QtWidgets.QPushButton(InputData)
        self.clearInputValues.setGeometry(QtCore.QRect(520, 820, 201, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearInputValues.setFont(font)
        self.clearInputValues.setObjectName("clearInputValues")

        self.retranslateUi(InputData)
        QtCore.QMetaObject.connectSlotsByName(InputData)

    def retranslateUi(self, InputData):
        _translate = QtCore.QCoreApplication.translate
        InputData.setWindowTitle(_translate("InputData", "Ввод исходных данных"))
        self.viewKnowledgeBase.setText(_translate("InputData", "Посмотреть базу знаний"))
        self.determineTypeAlloy.setText(_translate("InputData", "Определить вид сплава"))
        self.label.setText(_translate("InputData", "Ввод исходных данных"))
        self.label_2.setText(_translate("InputData", "Введенные значения"))
        self.clearInputValues.setText(_translate("InputData", "Очистить значения"))
