# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\selectionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectionWindow(object):
    def setupUi(self, selectionWindow):
        selectionWindow.setObjectName("selectionWindow")
        selectionWindow.resize(500, 301)
        selectionWindow.setMinimumSize(QtCore.QSize(500, 301))
        selectionWindow.setMaximumSize(QtCore.QSize(500, 301))
        self.openKnowledgeEditorWindow = QtWidgets.QPushButton(selectionWindow)
        self.openKnowledgeEditorWindow.setGeometry(QtCore.QRect(120, 50, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openKnowledgeEditorWindow.setFont(font)
        self.openKnowledgeEditorWindow.setObjectName("openKnowledgeEditorWindow")
        self.openInputDataWindow = QtWidgets.QPushButton(selectionWindow)
        self.openInputDataWindow.setGeometry(QtCore.QRect(120, 150, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openInputDataWindow.setFont(font)
        self.openInputDataWindow.setObjectName("openInputDataWindow")

        self.retranslateUi(selectionWindow)
        QtCore.QMetaObject.connectSlotsByName(selectionWindow)

    def retranslateUi(self, selectionWindow):
        _translate = QtCore.QCoreApplication.translate
        selectionWindow.setWindowTitle(_translate("selectionWindow", "Окно выбора"))
        self.openKnowledgeEditorWindow.setText(_translate("selectionWindow", "Редактор базы знаний"))
        self.openInputDataWindow.setText(_translate("selectionWindow", "Решатель задач"))
