# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\resultDescription.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Result(object):
    def setupUi(self, Result):
        Result.setObjectName("Result")
        Result.resize(850, 435)
        Result.setMinimumSize(QtCore.QSize(850, 435))
        Result.setMaximumSize(QtCore.QSize(850, 435))
        self.textEdit = QtWidgets.QTextEdit(Result)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 831, 421))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Result)
        QtCore.QMetaObject.connectSlotsByName(Result)

    def retranslateUi(self, Result):
        _translate = QtCore.QCoreApplication.translate
        Result.setWindowTitle(_translate("Result", "Описание результата"))
