# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\possibleValues.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PossiblesValues(object):
    def setupUi(self, PossiblesValues):
        PossiblesValues.setObjectName("PossiblesValues")
        PossiblesValues.resize(762, 600)
        PossiblesValues.setMinimumSize(QtCore.QSize(762, 507))
        PossiblesValues.setMaximumSize(QtCore.QSize(762, 600))
        PossiblesValues.setBaseSize(QtCore.QSize(762, 507))
        self.propertiesList = QtWidgets.QComboBox(PossiblesValues)
        self.propertiesList.setGeometry(QtCore.QRect(100, 10, 571, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.propertiesList.setFont(font)
        self.propertiesList.setObjectName("propertiesList")
        self.listWidget = QtWidgets.QListWidget(PossiblesValues)
        self.listWidget.setGeometry(QtCore.QRect(20, 70, 721, 241))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.inputLine = QtWidgets.QLineEdit(PossiblesValues)
        self.inputLine.setGeometry(QtCore.QRect(20, 480, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputLine.setFont(font)
        self.inputLine.setObjectName("inputLine")
        self.label = QtWidgets.QLabel(PossiblesValues)
        self.label.setGeometry(QtCore.QRect(30, 440, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(PossiblesValues)
        self.pushButton.setGeometry(QtCore.QRect(580, 460, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(PossiblesValues)
        self.label_4.setGeometry(QtCore.QRect(30, 550, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.inputLine_2 = QtWidgets.QLineEdit(PossiblesValues)
        self.inputLine_2.setGeometry(QtCore.QRect(20, 390, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputLine_2.setFont(font)
        self.inputLine_2.setObjectName("inputLine_2")
        self.label_2 = QtWidgets.QLabel(PossiblesValues)
        self.label_2.setGeometry(QtCore.QRect(30, 350, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(PossiblesValues)
        QtCore.QMetaObject.connectSlotsByName(PossiblesValues)

    def retranslateUi(self, PossiblesValues):
        _translate = QtCore.QCoreApplication.translate
        PossiblesValues.setWindowTitle(_translate("PossiblesValues", "Form"))
        self.label.setText(_translate("PossiblesValues", "Введите ..."))
        self.pushButton.setText(_translate("PossiblesValues", "Добавить"))
        self.label_4.setText(_translate("PossiblesValues", "Для удаления объекта из списка дважды кликните по нему"))
        self.label_2.setText(_translate("PossiblesValues", "Введите тип свойства (исчеляемый, перечислимый)"))
